myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('product/<int:id>', views.detail_view, name='detail'),
    path('api/checkout-session/<int:id>', views.create_checkout_session_view, name='api_checkout_session'),
    path('success', views.payment_success_view, name='success'),
    path('failed', views.payment_failed_view, name='failed'),
    path('create-product', views.create_product_view, name='createproduct'),
    path('update-product/<int:id>', views.update_product_view, name='updateproduct'),
    path('delete-product/<int:id>', views.delete_product_view, name='deleteproduct'),
    path('dashboard', views.dashboard_view, name='dashboard'),
    path('registration', views.user_registration_view, name='registration'),
    path('login', views.user_login_view, name='login'),
    path('logout', views.user_logout_view, name='logout'),
    path('purchases', views.purchases_view, name='purchases'),
    path('sales', views.sales_view, name='sales')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('myapp.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class CustomUser(AbstractUser):
    email = models.EmailField(max_length=100, unique=True)

    USERNAME_FIELD = 'username'
    # set this for the required fields except the USERNAME_FIELD
    REQUIRED_FIELDS = ['email']


class Product(models.Model):
    class Meta:
        ordering = ["pk"]

    seller = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=30, decimal_places=2)
    file = models.FileField(upload_to='uploads')
    total_sale_amount = models.DecimalField(max_digits=50, decimal_places=2, default=0.00)
    total_sale = models.IntegerField(default=0)

    def __str__(self):
        return f"id:{self.id} name:{self.name}"
    

class OrderDetail(models.Model):
    customer_email = models.EmailField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=30, decimal_places=2)
    stripe_session_id = models.CharField(max_length=300, default="")
    stripe_payment_intent = models.CharField(max_length=200, null=True)
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Product


class CustomAdminUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = "__all__"


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'file']
        # exclude = ['seller', 'total_sale_amount', 'total_sale']
        labels = {
            "name": "Title"
        }
        error_messages = {
            'description': {
                'max_length': 'Keep the description under 300 letters',
                'min_length': 'Description must be al least 5 Characters long'
            },
            'file': {
                'required': 'Please, Select a file!'
            }
        }

    description = forms.CharField(
        max_length = 300,
        min_length = 5,
        widget = forms.Textarea
    )
    


# class UserRegistrationForm(forms.ModelForm):
#     password = forms.CharField(label='Password', min_length=4, max_length=20, widget=forms.PasswordInput, error_messages={
#         "min_length": "Password must be atleast 4 characters long",
#         "max_length": "Please, Enter a shorter Password"
#     })
#     confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         fields = ['username', 'email']
        
#         labels = {
#             "email": "Email",
#         }

#     def clean(self):
#         cleaned_data = super().clean()
#         password = self.cleaned_data['password']
#         confirm_password = self.cleaned_data['confirm_password']
#         if password != confirm_password:
#             raise forms.ValidationError('Password Do not match')

class UserRegistrationForm(UserCreationForm):

    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'placeholder': 'Password'
        })
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'placeholder': 'Confirm passowrd'
        })
        
    )
    email = forms.CharField(
        required=True,
        error_messages= {
            'required': 'Must provide an unused email'
        },
        widget = forms.EmailInput(attrs={'placeholder': 'Email Address'})
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
        }
        error_messages = {
            'username': {
                'required': 'Must provide an username'
            }
        }


class UserLoginForm(forms.Form):
    email = forms.EmailField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Email address'}))
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.http import JsonResponse, HttpResponseNotFound, Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
from django.db.models import Sum
import stripe, json
import os
import datetime

from .models import Product, OrderDetail, CustomUser
from .forms import ProductForm, UserRegistrationForm, UserLoginForm
# Create your views here.

def index_view(request):
    if request.method == 'POST':
        search_item = request.POST['search']
        if len(search_item) == 0:
            return redirect('myapp:index')
        else:
            products = Product.objects.filter(name__icontains=search_item)
            paginator = Paginator(products, 4)
            page = request.GET.get('page')
            try:
                products = paginator.page(page)
            except PageNotAnInteger:
                products = paginator.page(1)
            except EmptyPage:
                products = paginator.page(paginator.num_pages)
            return render(request, 'myapp/index.html', {"products": products})

    products = Product.objects.all()
    paginator = Paginator(products, 4)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'myapp/index.html', {"products": products})



def detail_view(request, id):
    product = Product.objects.get(id=id)
    stripe_publishable_key = settings.STRIPE_PUBLISHABLE_KEY
    return render(request, 'myapp/detail.html', {"product": product, "stripe_publishable_key": stripe_publishable_key})


@login_required(login_url='myapp:login')
@csrf_exempt
def create_checkout_session_view(request, id):
    # getting json data from AJAX request
    request_data = json.loads(request.body)
    if not 'email' in request_data:
        messages.info(request, "Please, Log in to continue")
        return redirect('myapp:login')

    product = Product.objects.get(id=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    # create a stripe checkout session object
    try:
        checkout_session = stripe.checkout.Session.create(
            customer_email = request_data['email'],
            payment_method_types = ['card'],
            line_items = [
                {
                    'price_data':{
                        'currency': 'usd',
                        'product_data': {
                            'name': product.name
                        },
                        'unit_amount': int(product.price * 100)
                    },
                    'quantity': 1,
                }
            ],
            mode = 'payment',
            success_url = request.build_absolute_uri(reverse('myapp:success')) + 
            "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url = request.build_absolute_uri(reverse('myapp:failed'))
        )

        # creating order instance and saving into db
        order = OrderDetail()
        order.customer_email = request_data['email']
        order.product = product
        order.amount = product.price
        order.stripe_session_id = checkout_session.id
        order.save()
        return JsonResponse({'sessionId': checkout_session.id})
    except:
        return JsonResponse({'error': 'Internal Error'}, status=500)


@login_required(login_url='myapp:login')
def payment_success_view(request):
    #get the sessionId form the successurl: ?session_id={CHECKOUT_SESSION_ID}
    session_id = request.GET.get('session_id')

    if session_id is None:
        return HttpResponseNotFound()
    
    # retrive the session info from stripe
    stripe.api_key = settings.STRIPE_SECRET_KEY
    try:
        session = stripe.checkout.Session.retrieve(session_id)
        order = get_object_or_404(OrderDetail, stripe_session_id=session.id)
        if session.payment_intent == None:
            raise Http404("Unauthorized access")
        order.stripe_payment_intent = session.payment_intent
        order.has_paid = True
        product = Product.objects.get(id=order.product.id)
        product.total_sale_amount = product.total_sale_amount + order.amount
        product.total_sale = product.total_sale + 1
        product.save()
        order.save()
        return render(request, 'myapp/payment_success.html', {"order": order})
    except:
        raise Http404("session id does not exist")



@login_required(login_url='myapp:login')
def payment_failed_view(request):
    return render(request, 'myapp/payment_failed.html')


@login_required(login_url='myapp:login')
def create_product_view(request):
    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES)
        
        if product_form.is_valid():
            new_product = product_form.save(commit=False)
            new_product.seller = request.user
            new_product.save()
            return redirect('myapp:dashboard')

    else:
        product_form = ProductForm()

    return render(request, 'myapp/create_product.html', {
        "product_form": product_form,
        "path": "/createproduct"
        })



@login_required(login_url='myapp:login')
def update_product_view(request, id):
    try:
        product = Product.objects.get(id=id)
        current_file_path = product.file.path
    except Exception as err:
        return Http404('product not found')

    if product.seller != request.user:
        messages.error(request, 'invalid request')
        return redirect('myapp:dashboard')

    if request.method == "POST":
        product_form = ProductForm(request.POST, request.FILES, instance=product)
        if product_form.is_valid():
            if request.FILES:
                if os.path.exists(current_file_path):
                    os.remove(current_file_path)
            new_product_fomr = product_form.save()
            return redirect('myapp:dashboard')
    else:
        product_form = ProductForm(instance=product)

    return render(request, 'myapp/create_product.html', {
        "product_form": product_form,
        "product": product,
        "update": True
    })





@login_required(login_url='myapp:login')
def delete_product_view(request, id):
    try:
        product = Product.objects.get(id=id)

        if product.seller != request.user:
            messages.error(request, 'invalid request')
            return redirect('myapp:dashboard')

        if request.method == "POST":
                if product.file:
                    file_path = product.file.path
                    if os.path.exists(file_path):
                        os.remove(file_path)
                product.delete()
                return redirect(reverse("myapp:dashboard"))

        return render(request, 'myapp/delete_product.html', { "product": product})
    except:
        raise Http404('Product Id does not exist')





@login_required(login_url='myapp:login')
def dashboard_view(request):
    if request.method == 'POST':
        search_item = request.POST['search']
        if len(search_item) == 0:
            return redirect('myapp:index')
        else:
            search_product = Product.objects.filter(name__icontains=search_item, seller=request.user)
            return render(request, 'myapp/dashboard.html', 
            {"products": search_product, "path": "/dashboard"})

    products = Product.objects.filter(seller=request.user)
    return render(request, 'myapp/dashboard.html', {"products": products, "path": "/dashboard"})





def user_registration_view(request):
    if request.method == "POST":
        registration_form = UserRegistrationForm(request.POST)

        if registration_form.is_valid():
            new_user = registration_form.save()
            return redirect('myapp:dashboard')
    else:
        registration_form = UserRegistrationForm()

    return render(request, 'myapp/registration_form.html', {"form": registration_form, "path": "/register"})



def user_login_view(request):
    if request.method == 'POST':
        form_data = UserLoginForm(request.POST)

        if form_data.is_valid():
            email = form_data.cleaned_data['email']
            password = form_data.cleaned_data['password']
            user_info = CustomUser.objects.get(email=email)
            valid_user = authenticate(request, username=user_info.username, password=password)
            if valid_user is not None:
                login(request, valid_user)
                return redirect('myapp:dashboard')
            else:
                return render(request, 'myapp/login_form.html', {"form": form_data, "error": True})
    else:
        form_data = UserLoginForm()
    if 'next' in request.GET:
        print(request.GET['next'])
        messages.info(request, 'Please, log in to continue')
    return render(request, 'myapp/login_form.html', {"form": form_data, "path": '/login'})



def user_logout_view(request):
    logout(request)
    return redirect('myapp:index')





@login_required(login_url='myapp:login')
def purchases_view(request):
    print(request.user.email)
    orders = OrderDetail.objects.filter(has_paid=True, customer_email=request.user.email)
    return render(request, 'myapp/purchases.html',
    {"orders": orders, "path": "/purchases"})



@login_required(login_url='myapp:sales')
def sales_view(request):
    orders = OrderDetail.objects.filter(product__seller = request.user, has_paid=True)
    total_sales = orders.aggregate(Sum('amount'))
    print(total_sales)

    # last 365 days
    last_year = datetime.date.today() - datetime.timedelta(days=365)

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block css %} 
      {% comment %} add css here {% endcomment %}
    {% endblock %}
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
  </head>
  <body id='body'>

    <nav class="shadow-lg fixed left-0 w-full top-0 z-10 bg-white">
      <div class="flex flex-wrap justify-between items-center py-4 mx-6">
        <a class="flex items-center" href="{% url 'myapp:index' %}">
          <img class="h-9 mr-3" src="https://cdn2.iconfinder.com/data/icons/Siena/256/shopping_basket%20red.png" alt="">
          <span class="text-xl font-semibold">Digital Marketplace</span>
        </a>
        <div>
          {% if user.is_authenticated %}
            <a class="text-sm mr-6 hover:text-black {% if path == '/dashboard' %} text-black font-bold {% else %} text-gray-700 font-medium {% endif %}" href="{% url 'myapp:dashboard' %}">Dashboard</a>
            <a class="text-sm mr-6 hover:text-black {% if path == '/sales' %} text-black font-bold {% else %} text-gray-700 font-medium {% endif %}" href="{% url 'myapp:sales' %}">Sales</a>
            <a class="text-sm mr-6 hover:text-black {% if path == '/createproduct' %} text-black font-bold {% else %} text-gray-700 font-medium {% endif %}" href="{% url "myapp:createproduct" %}">Create Product</a>
            <a class="text-sm mr-6 hover:text-black {% if path == '/purchases' %} text-black font-bold {% else %} text-gray-700 font-medium {% endif %}" href="{% url 'myapp:purchases' %}">My Purchase</a>
            <form class="inline" action="/logout" method='POST'>
              {% csrf_token %}
              <button class="text-sm font-medium hover:text-black mr-6 text-gray-700">Logout</button>
            </form>
            {% else %}
              <a class="text-sm mr-6 hover:text-black {% if path == '/login' %} text-black font-bold {% else %} text-gray-700 font-medium {% endif %}" href="{% url 'myapp:login' %}">Login</a>
              <a class="text-sm mr-6 hover:text-black {% if path == '/register' %} text-black font-bold {% else %} text-gray-700 font-medium {% endif %}" href="{% url 'myapp:registration' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% block body %}
      {% comment %} child content goes here {% endcomment %}
    {% endblock %}
  </body>
</html>

myapp/templates/myapp/create_product.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'myapp/form.css' %}">
{% endblock %}

{% block body %}

    <div class="w-[30rem] my-[6rem] mx-auto shadow-2xl py-4 px-5 rounded-md">
        <div class="font-bold text-slate-700 text-2xl pb-4 text-center">
            {% if update %}
                Update Product Info
            {% else %}
                Create Product
            {% endif %}
        </div>
        {% if error %}
            <div class="bg-red-500 text-white font-semibold text-lg w-full text-center">
                Invalid input data
            </div>
        {% endif %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in product_form %}
                <div class="form-control {% if field.errors %} error {% endif %}">
                    <p class="font-semibold text-xl my-2">
                        {{field.label_tag}}
                    </p>
                    <div>
                        {{field}}
                    </div>
                    <p>{{field.errors}}</p>
                </div>
            {% endfor %}
            <button class="bg-green-600 px-4 py-2 text-white font-semibold mt-4 mr-6 rounded-md w-full hover:bg-green-800" 
            type="submit">
            {% if update %}
                Update
            {% else %}
                Add
            {% endif %}
            </button>
            {% if update %}
            <a href="{% url 'myapp:deleteproduct' product.id %}">
            <div class="w-full mt-4 text-center bg-red-600 hover:bg-red-800 px-4 py-2 text-white font-semibold rounded-md">
                    Delete
            </div>
            </a>
            {% endif %}
        </form>
    </div>

{% endblock %}

myapp/templates/myapp/dashboard.html
{% extends 'myapp/base.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'myapp/messages.css' %}">
{% endblock %}

{% block body %}


<div class="mt-[7rem] mx-12">
    {% for message in messages %}
        <p class = "errorlist">{{message}}</p>
    {% endfor %}
    <div>
        <div class='flex justify-between flex-wrap'>
            <a href="{% url 'myapp:dashboard' %}" class="text-2xl font-bold my-4">My Products</a>
            <div class="search-bar  mt-[1rem] ">
                <form class="search-form text-end " action="{% url 'myapp:dashboard' %}" method="POST">
                    {% csrf_token %}
                    <input class="border-2 border-slate-500 focus:border-blue-600 outline-0 px-3 py-1 mr-0 rounded-md w-[15rem] h-[2.4rem]" required type="text" name="search" placeholder="search product">
                    <button class="search-btn px-3 py-1.5 rounded-md text-white font-semibold bg-slate-600 hover:bg-slate-800" type="submit">Search</button>
                </form>
            </div>
            <a class="my-4 px-4 py-2 bg-green-600 hover:bg-green-800 font-semibold text-lg text-white rounded-md" href="{% url 'myapp:createproduct' %}">New Product</a>
            
        </div>
        {% if products|length > 0 %}
            <div class="product-container flex flex-col">
                {% for product in products %}
                    <div class="flex justify-between px-4 py-4 shadow-lg my-4">
                        <div class="product-info flex items-center gap-4 mr-6 flex-1">
                            <div class="product-image h-[100px] w-[100px] overflow-hidden flex">
                                <img class="w-full object-cover items-center" src="{{ product.file.url }}" alt="">
                            </div>
                            <div>
                                <div class="my-2 text-xl font-bold">{{product.name}}</div>
                                <div class="my-2 font-semibold">${{product.price}}</div>
                                <div class="my-2">
                                    <a class="px-2 py-1 bg-green-600 hover:bg-green-800 text-white font-semibold rounded-sm"
                                    href="{% url 'myapp:updateproduct' product.id %}">
                                        Update
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="flex flex-col justify-center gap-2 mr-6 flex-1 text-center">
                            <p class="text-2xl font-bold text-green-700">${{product.total_sale_amount}}</p>
                            <p class="">Total earnings</p>
                        </div>
                        <div class="flex flex-col justify-center gap-2 flex-1 text-center">
                            <p class="text-2xl font-bold">{{product.total_sale}}</p>
                            <p class="">Total sales</p>
                        </div>
                    </div>
                {% endfor %}
        </div>
        {% else %}
        <div class="text-4xl font-bold mt-[10rem] text-center">
            Product Not Found
        </div>
        {% endif %}
        
        
    </div>
    
</div>


{% endblock %}

myapp/templates/myapp/delete_product.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="my-20 p-5 flex flex-col items-center">
        <div class="w-[350px] h-[250px] overflow-hidden flex items-center">
            <img class=" object-cover w-full" src="{{product.file.url}}" alt="">
        </div>
        <div id="product-detail" class="p-4">
            <div class = "text-3xl font-bold mb-4">{{product.name}}</div>
            <div class="text-xl mb-4">{{product.description}}</div>
            <div class="text-xl text-green-700 font-bold mb-4">${{product.price}}</div>
            <form class="my-8" action="{% url 'myapp:deleteproduct' product.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="bg-red-500 hover:bg-red-800 text-white font-semibold text-xl mr-4
                py-2 px-6 rounded-md">Confirm Delete</button>
                <a class="bg-slate-700 hover:bg-slate-900 text-white font-semibold text-xl mr-4
                py-2 px-6 rounded-md" href="{% url 'myapp:index' %}">Cancel</a>
            </form>
        </div>
        
    </div>

{%endblock%}


    
    

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div id="container" class="my-[4.5rem] p-6">
        <div class="product-container flex gap-6">
            <div class="w-[400px] h-[400px] overflow-hidden">
                <img class=" object-cover" src="{{product.file.url}}" alt="">
            </div>
            <div id="product-detail" class="p-4">
                <div class = "text-3xl font-bold mb-4">{{product.name}}</div>
                <div class="text-xl mb-4">{{product.description}}</div>
                <div class="text-xl text-green-700 font-bold mb-4">${{product.price}}</div>
                <div class="my-8">
                    <button id="checkout-button" class="bg-green-600 text-white font-semibold text-xl 
                    py-2 px-6 rounded-md">Buy</button>
                </div>
            </div>
        </div>
    </div>
    <script src="https://js.stripe.com/v3/"></script>
    <script type='text/javascript'>
        //create an stipe instance
        const stripe = Stripe('{{stripe_publishable_key}}');
        const productDetailDiv = document.getElementById('product-detail');
        const containerDiv = document.getElementById('container');
        
        const checkoutBtn = document.getElementById('checkout-button');
        checkoutBtn.addEventListener('click', function() {
            console.log('clicked');
            const errorDiv = document.getElementById('error-div');
                if(errorDiv) {
                    productDetailDiv.removeChild(errorDiv);
                }

            // getting the user email
            const userEmail = '{{request.user.email}}';
            console.log(userEmail);

            if(userEmail.length === 0) {
                {% comment %} const newErrorDiv = document.createElement("div");
                newErrorDiv.id = 'error-div';
                newErrorDiv.textContent = "Please, Login to Purchase this product";
                newErrorDiv.style.color = "white";
                newErrorDiv.style.width = "100%";
                newErrorDiv.style.background = "rgba(0, 0, 255, 0.5)";
                newErrorDiv.style.marginBottom = "10px";
                newErrorDiv.style.padding = "10px 0px";
                newErrorDiv.style.textAlign = "center"; 
                containerDiv.prepend(newErrorDiv);
                return; {% endcomment %}

                window.location.href = '/login?next=detail';
                return;
            }
            fetch('{% url "myapp:api_checkout_session" product.id %}', {
                method: 'POST',
                body: JSON.stringify({'email': userEmail}),
            })
            .then(response => {
                if(!response.ok) {
                    throw new Error('Internal error');
                }
                return response.json();
            })
            .then(data => {
                return stripe.redirectToCheckout({sessionId: data.sessionId});
            })
            .catch(err => {
                const newErrorDiv = document.createElement("div");
                newErrorDiv.id = 'error-div';
                newErrorDiv.textContent = "Apologies. Could not perform the action. Try again later";
                newErrorDiv.style.color = "red";
                newErrorDiv.style.position = "absolute";
                newErrorDiv.style.top = "0";
                newErrorDiv.style.left = "0"; 
                containerDiv.appendChild(newErrorDiv);
                console.log(err);
            })
            
        })
    </script>

{%endblock%}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body %}

<div class="index-body flex flex-col flex-wrap mt-[5rem]">
    <div class="search-bar mx-[6rem] mt-[1rem] ">
        <form class="search-form text-end " action="{% url 'myapp:index' %}" method="POST">
            {% csrf_token %}
            <input class="border-2 border-slate-500 focus:border-blue-600 outline-0 px-3 py-1 mr-0 rounded-md w-[20rem] h-[2.4rem]" required type="text" name="search" placeholder="search product">
            <button class="search-btn px-3 py-1.5 rounded-md text-white font-semibold bg-slate-600 hover:bg-slate-800" type="submit">Search</button>
        </form>
    </div>
    <div class="product-container flex flex-col flex-wrap sm:justify-evenly sm:flex-row">
        {% if products|length > 0 %}
            {% for product in products %}
                <div class='product-card shadow-xl rounded-lg my-5 mx-auto gap-4 w-[450px] sm:w-[350px] sm:flex-shrink-0 sm:mx-10 flex flex-col justify-between'>
                    <div class="product-image h-[250px] w-full overflow-hidden my-2 flex">
                        <img class=" items-center w-full" src="{{ product.file.url }}" alt="">
                    </div>
                    <div class="product-body mx-5">
                        <div class="font-bold pb-1">
                            {{product.name}}
                        </div>
                        <div class=" pb-1">
                            {{product.description}}
                        </div>
                        <div class="font-bold text-green-700 pb-1">
                            ${{product.price|floatformat:2}}
                        </div>
                        <div class=" my-4">
                            <a class=" bg-green-600 text-white px-4 py-1 font-semibold" 
                            href="{% url 'myapp:detail' product.id %}">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
            <div class="text-4xl font-bold mt-[10rem]">
                Product not found
            </div>
        {% endif %}
    </div>
    {% if products|length > 0 %}
        {% include 'myapp/paginator.html' with page=products %}
    {% endif %}
</div>
{%endblock%}

myapp/templates/myapp/paginator.html
<div class="mb-6 text-center text-lg">
    <span>
        {% if page.has_previous %}
            <a class="font-semibold text-blue-800" href="{% url 'myapp:index' %}?page={{page.previous_page_number}}">Previous</a>
        {% endif %}

        <span class="mx-6 font-semibold">
            Page {{page.number}} of {{page.paginator.num_pages}}
        </span>

        {% if page.has_next %}
            <a class="font-semibold text-blue-800" href="{% url 'myapp:index' %}?page={{page.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>

myapp/templates/myapp/payment_failed.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="grid place-items-center h-screen content-center">
        <div class = "text-3xl text-red-600 font-bold my-8">Payment Failed</div>
        <a class="text-2xl bg-slate-600 text-white font-semibold py-4 px-8 rounded-xl my-8 hover:bg-slate-800" 
        href="{% url 'myapp:index' %}" >Go to Home</a>
    </div>

{% endblock %}